Models/Musteriler.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;

namespace IcraTakipProgrami.Models;

public partial class Musteriler
{
    public int Id { get; set; }

    public int MusteriNo { get; set; }

    public string Ad { get; set; } = null!;

    public string Soyad { get; set; } = null!;

    public string Tckn { get; set; } = null!;

    public string? DogumYeri { get; set; }

    public DateOnly? DogumTarihi { get; set; }

    public string? Cinsiyet { get; set; }

    public string? BabaAd { get; set; }

    public string? AnneAd { get; set; }

    public int? Sehir { get; set; }

    public int? Ilce { get; set; }

    public string? Semt { get; set; }

    public bool MistralMusteriTipi { get; set; }

    public bool HayattaMı { get; set; }

    public DateOnly? EklenmeTarihi { get; set; }

    public DateTime? GuncellenmeTarihi { get; set; }

    public bool Silindimi { get; set; }

    public string? EkleyenKullanici { get; set; }

    public string? GuncelleyenKullanici { get; set; }

    public virtual Sehirler? SehirNavigation { get; set; }

    public virtual ICollection<Urunler> Urunlers { get; set; } = new List<Urunler>();


}

Controllers/MusterilerController.cs
using IcraTakipProgrami.Models;
using IcraTakipProgrami.Models.Ihtar;
using IcraTakipProgrami.Models.Musteri;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace IcraTakipPrototip.Controllers
{
    public class MusterilerController : Controller
    {
        private readonly StajProjesiContext _context;

        private IHttpContextAccessor _httpContextAccessor;


        public MusterilerController(StajProjesiContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;

        }


        public IActionResult Create()
        {
            return View();
        }

        public IActionResult IlceSet(int sehirId)
        {
            var ilceListesi = _context.Ilcelers.Where(p => p.Sehirid == sehirId).ToListAsync();

            return Json(new { ilceListesi });
        }

        public IActionResult IlceUpdateSet(int sehirId)
        {
            var ilceListesi = _context.Ilcelers.Where(p => p.Sehirid == sehirId).ToListAsync();

            return Json(new { ilceListesi });
        }

        public async Task<IActionResult> CreateModal()
        {
            var sehirListesi = await _context.Sehirlers.ToListAsync();
            //var ilceListesi = await _context.Ilcelers.Where(p>) .ToListAsync();

            var sehirSelectList = new SelectList(sehirListesi, "Id", "Sehiradi");

            //var ilceSelectList = new SelectList(ilceListesi, "Id", "Ilceadi");


            var model = new MusteriCreateViewModel
            {
                SehirEkleListesi = sehirSelectList,
                //IlceEkleListesi = ilceSelectList
            };
            return PartialView("Create", model);
        }

        [HttpGet]
        public async Task<IActionResult> EditModal(int id)
        {
            var sehirListesi = await _context.Sehirlers.ToListAsync();
            var sehirSelectList = new SelectList(sehirListesi, "Id", "Sehiradi");



            //var avukat = _context.Musterilers.Find(id);
            //if (avukat == null)
            //{
            //    return NotFound();
            //}
            //return PartialView("Edit", avukat);

            var musteri = await _context.Musterilers.FindAsync(id);
            if (musteri == null)
            {
                return NotFound();
            }



            var model = new MusteriCreateViewModel
            {


                Id = musteri.Id,
                Ad = musteri.Ad,
                Soyad = musteri.Soyad,
                Tckn = musteri.Tckn,
                DogumTarihi = musteri.DogumTarihi,
                DogumYeri = musteri.DogumYeri,
                Cinsiyet = musteri.Cinsiyet,
                BabaAd = musteri.BabaAd,
                AnneAd = musteri.AnneAd,
                Sehir = musteri.Sehir,
                Ilce = musteri.Ilce,
                Semt = musteri.Semt,
                MistralMusteriTipi = musteri.MistralMusteriTipi,
                HayattaMı = musteri.HayattaMı,
                SehirEkleListesi = sehirSelectList
            };

            return PartialView("Edit", model);
        }



        public async Task<IActionResult> Index()
        {
            var td = from musteriler in _context.Musterilers
                     join sehir in _context.Sehirlers on musteriler.Sehir equals sehir.Id
                     join ilce in _context.Ilcelers on musteriler.Ilce equals ilce.Id

                     select new MusteriViewModel
                     {
                         Id = musteriler.Id,
                         Ad = musteriler.Ad,
                         Soyad = musteriler.Soyad,
                         Tckn = musteriler.Tckn,
                         DogumTarihi = musteriler.DogumTarihi,
                         DogumYeri = musteriler.DogumYeri,
                         Cinsiyet = musteriler.Cinsiyet,
                         BabaAd = musteriler.BabaAd,
                         AnneAd = musteriler.AnneAd,
                         Sehir = sehir.Id,
                         SehirAd = sehir.Sehiradi,
                         Ilce = ilce.Id,
                         IlceAd = ilce.Ilceadi,
                         Semt = musteriler.Semt,
                         MistralMusteriTipi = musteriler.MistralMusteriTipi,
                         HayattaMı = musteriler.HayattaMı,

                     };

            return View(td);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Musteriler model)
        {
            var musteri = new Musteriler
            {
                Id = model.Id,
                Ad = model.Ad,
                Soyad = model.Soyad,
                Tckn = model.Tckn,
                DogumTarihi = model.DogumTarihi,
                DogumYeri = model.DogumYeri,
                Cinsiyet = model.Cinsiyet,
                BabaAd = model.BabaAd,
                AnneAd = model.AnneAd,
                Sehir = model.Sehir,
                Ilce = model.Ilce,
                Semt = model.Semt,
                MistralMusteriTipi = model.MistralMusteriTipi,
                HayattaMı = model.HayattaMı,

            };

            var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            model.EkleyenKullanici = userId;
            model.EklenmeTarihi = DateOnly.FromDateTime(DateTime.Now);

            _context.Musterilers.Add(musteri);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Musteri = await _context.Musterilers.FindAsync(id);



            if (Musteri == null)
            {
                return NotFound();
            }

            return View(Musteri);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Musteriler model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            try
            {
                var userId = _httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value;

                model.GuncelleyenKullanici = userId;
                model.GuncellenmeTarihi = DateTime.Now;
                _context.Update(model);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (_context.Musterilers.Any(a => a.Id == model.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");

            return View(model);

        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var musteri = await _context.Musterilers.FindAsync(id);
            if (musteri == null)
            {
                return NotFound();
            }
            return View(musteri);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var musteri = await _context.Musterilers.FindAsync(id);
            if (musteri == null)
            {
                return NotFound();
            }
            _context.Musterilers.Remove(musteri);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }

    }
}

Views/Musteriler/Create.cshtml
@model IcraTakipProgrami.Models.Musteri.MusteriCreateViewModel
@{
        <div class="container">
        <h2>Müşteri Oluştur</h2>
            <form asp-controller="Musteriler" asp-action="Create" method="post">
                <div class="row justify-content-center">
                    <div class="col-sm-6">
                <div class="mb-3">
                    <label asp-for="Ad" class="form-label">Ad</label>
                            <input maxlength="15" asp-for="Ad" class="form-control" required>

                </div>
                <div class="mb-3">
                    <label asp-for="Soyad" class="form-label">Soyad</label>
                            <input maxlength="15" asp-for="Soyad" class="form-control" required>
                </div>
                <div class="mb-3">
                    <label asp-for="Tckn" class="form-label">Tckn</label>
                            <input maxlength="11" asp-for="Tckn" class="form-control" required>
                </div>
               
                <div class="mb-3">
                    <label asp-for="DogumTarihi" class="form-label">Doğum Tarihi</label>
                            <input maxlength="15" type="date" asp-for="DogumTarihi" class="form-control" required>
                </div>
                    

                <div class="mb-3">
                            <label asp-for="Cinsiyet" class="form-label">Cinsiyet</label>
                            <select asp-for="Cinsiyet" class="form-select form-select-md">
                                <option value="">Seçiniz</option>
                                <option value="Erkek">Erkek</option>
                                <option value="Kadın">Kadın</option>
                            </select>
                </div>
                   
                <div class="mb-3">
                    <label asp-for="BabaAd" class="form-label">Baba Ad</label>
                    <input maxlength ="15" asp-for="BabaAd" class="form-control">
                </div>
                    </div>

                    <div class="col-sm-6">
                <div class="mb-3">
                    <label asp-for="AnneAd" class="form-label">Anne Ad</label>
                    <input maxlength="15" asp-for="AnneAd" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="Sehir" class="form-label">Şehirler</label>
                    <select itemid="sehirDropDown" onchange="sehirchange()" class="form-select form-select-md" asp-for="Sehir">
                                <option value=""> Seçiniz</option>
                                @foreach (var sehir in Model.SehirEkleListesi)
                                {
                                        <option itemid="sehirId" value="@sehir.Value">@sehir.Text</option>
                                }
                                
                                
                            </select>
                </div>
                        <div class="mb-3">
                            <label asp-for="Ilce" class="form-label">İlçeler</label>
                            <select itemid="ilceDropDown" class="form-select form-select-md" asp-for="Ilce">
                                <option value=""> Seçiniz</option>
                              
                               
                            </select>
                        </div>
              
                <div class="mb-3">
                    <label asp-for="Semt" class="form-label">Semt</label>
                    <input asp-for="Semt" class="form-control">
                </div>
                <div class="mb-3">
                    <label asp-for="MistralMusteriTipi" class="form-label">Mistral Musteri Tipi</label>
                            <select asp-for="MistralMusteriTipi" class="form-select form-select-md" required>
                        <option  value="">Seçiniz</option>
                                <option value="Bireysel">Bireysel</option>
                                <option value="Kurumsal">Kurumsal</option>
                    </select>
                </div>
                <div class="mb-3">
                    <label asp-for="HayattaMı" class="form-label">Hayatta Mı</label>
                    <input type="checkbox" class="form-check-input" asp-for="HayattaMı" style="margin-left: 10px;">
                </div>
                <div class="mb-3">
                    <button style="margin-bottom: 40px;" type="submit" class="btn btn-primary"> Kaydet</button>
                </div>
                </div>
                </div>
            </form>
        </div>
}


            <script>


    function sehirchange() {
        var secilenSehirId = document.getElementById('Sehir').value;
        var url = '/Musteriler/IlceSet';
        // AJAX ile ilgili şehrin ilçelerini getir
        $.ajax({
            url: url, // İlçeleri getirilecek Action'ın URL'si
            type: 'GET',
            data: { sehirId: secilenSehirId }, // Seçilen şehir ID'sini parametre olarak gönder
            success: function (data) {
                debugger;
                // Başarılı bir şekilde veriler alındığında yapılacak işlemler
                // İlçe dropdown listesini temizle
                $('#Ilce').empty();
                // Gelen verileri ilçe dropdown listesine ekle

                for (var i = 0; i < data.ilceListesi.result.length; i++) {
                    $('#Ilce').append('<option value="' + data.ilceListesi.result[i].id + '">' + data.ilceListesi.result[i].ilceadi + '</option>');
                }

            },
            error: function () {
                // Hata durumunda yapılacak işlemler
                alert('Bir hata oluştu, ilçeler getirilemedi.');
            }
        });
    }
            </script>

Views/Musteriler/Delete.cshtml
@model IcraTakipProgrami.Models.Musteriler
@{
    <p>
        <b>@Model.Ad @Model.Soyad</b> isimli müşteriyi silmek istiyor musunuz?

        <form asp-action="Delete" method="post">
            <input type="hidden" name="id" value="@Model.Id">
            <button type="submit" class="btn btn-danger">Evet</button>
            <a asp-action="Index" class="btn btn-primary">Hayır</a>
        </form>
    </p>
}

Views/Musteriler/Edit.cshtml
@model IcraTakipProgrami.Models.Musteri.MusteriCreateViewModel
@{
    <div class="container">
        <h2>Müşteri Güncelle</h2>

        <form asp-controller="Musteriler" asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id">
            <div class="row justify-content-center">

            <div class="col-sm-6">

            <div class="mb-3">
                <label asp-for="Ad" class="form-label">Ad</label>
                <input asp-for="Ad" value="@Model.Ad?.Trim()" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Soyad" class="form-label">Soyad</label>
                <input asp-for="Soyad" value="@Model.Soyad?.Trim()" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Tckn" class="form-label">Tckn</label>
                <input asp-for="Tckn" value="@Model.Tckn?.Trim()" class="form-control">
            </div>
          
            <div class="mb-3">
                <label asp-for="DogumTarihi" class="form-label">Doğum Tarihi</label>
                <input type="date" asp-for="DogumTarihi"  class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="Cinsiyet" class="form-label">Cinsiyet</label>
                <select asp-for="Cinsiyet" class="form-select form-select-md">
                    <option  value="">Seçiniz</option>
                    <option value="Erkek">Erkek</option>
                    <option value="Kadın">Kadın</option>
                </select>
            </div>
            <div class="mb-3">
                <label asp-for="BabaAd" class="form-label">Baba Ad</label>
                <input asp-for="BabaAd" value="@Model.BabaAd?.Trim()" class="form-control">
            </div>
            </div>
            <div class="col-sm-6">

            <div class="mb-3">
                <label asp-for="AnneAd" class="form-label">Anne Ad</label>
                <input asp-for="AnneAd" value="@Model.AnneAd?.Trim()" class="form-control">
            </div>
                    <div class="mb-3">
                        <label asp-for="Sehir" class="form-label">Şehirler</label>
                        <select itemid="sehirDropDown" onchange="sehirchange()" class="form-select form-select-md" asp-for="Sehir">
                            <option value=""> Seçiniz</option>
                            @foreach (var sehir in Model.SehirEkleListesi)
                            {
                                <option itemid="sehirId" value="@sehir.Value">@sehir.Text</option>
                            }

                        </select>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Ilce" class="form-label">İlçeler</label>
                        <select itemid="ilceDropDown" class="form-select form-select-md" asp-for="Ilce">
                            <option value=""> Seçiniz</option>


                        </select>
                    </div>
            <div class="mb-3">
                <label asp-for="Semt" class="form-label">Semt</label>
                <input asp-for="Semt" value="@Model.Semt?.Trim()" class="form-control">
            </div>
            <div class="mb-3">
                <label asp-for="MistralMusteriTipi" class="form-label">Mistral Musteri Tipi</label>
                <select asp-for="MistralMusteriTipi" class="form-select form-select-md" required>
                    <option value="">Seçiniz</option>
                    <option value="Bireysel">Bireysel</option>
                    <option value="Kurumsal">Kurumsal</option>
                </select>
            </div>
            <div class="mb-3">
                <label asp-for="HayattaMı" class="form-label">Hayatta Mı</label>
                <input type="checkbox" class="form-check-input" asp-for="HayattaMı" style="margin-left: 10px;">
            </div>
            </div>
            </div>

            <div class="mb-3">
                <button style="margin-bottom: 40px;" type="submit" class="btn btn-primary"> Güncelle</button>
            </div>
        </form>

    </div>
}
<script>


    function sehirchange() {
        var secilenSehirId = document.getElementById('Sehir').value;
        var url = '/Musteriler/IlceSet';
        // AJAX ile ilgili şehrin ilçelerini getir
        $.ajax({
            url: url, // İlçeleri getirilecek Action'ın URL'si
            type: 'GET',
            data: { sehirId: secilenSehirId }, // Seçilen şehir ID'sini parametre olarak gönder
            success: function (data) {
                debugger;
                // Başarılı bir şekilde veriler alındığında yapılacak işlemler
                // İlçe dropdown listesini temizle
                $('#Ilce').empty();
                // Gelen verileri ilçe dropdown listesine ekle

                for (var i = 0; i < data.ilceListesi.result.length; i++) {
                    $('#Ilce').append('<option value="' + data.ilceListesi.result[i].id + '">' + data.ilceListesi.result[i].ilceadi + '</option>');
                }

            },
            error: function () {
                // Hata durumunda yapılacak işlemler
                alert('Bir hata oluştu, ilçeler getirilemedi.');
            }
        });
    }
</script>

Views/Musteriler/index.cshtml
@model IEnumerable<IcraTakipProgrami.Models.Musteri.MusteriViewModel>

<div class="container">


    <div class="modal fade bd-example-modal-lg" id="create" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <!-- Modal içeriği buraya gelecek -->
            </div>
        </div>
    </div>

    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="editModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content halildeneme">
                <!-- AJAX isteği sonucunda dönen HTML içeriği buraya yerleştirilecek -->
            </div>
        </div>
    </div>


    <div class="table-responsive" style="max-width: 100%; overflow-x: auto;">
        <button type="button" class="btn btn-primary mb-3" style="float:right" onclick="Create()">Müşteri Ekle</button>

        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Ad</th>
                    <th scope="col">Soyad</th>
                    <th scope="col">TCKN</th>
                    <th scope="col">Doğum Tarihi</th>
                    <th scope="col">Cinsiyet</th>
                    <th scope="col">Baba Adı</th>
                    <th scope="col">Anne Adı</th>
                    <th scope="col">Şehir</th>
                    <th scope="col">İlçe</th>
                    <th scope="col">Semt</th>
                    <th scope="col">Mistral Müşteri Tipi</th>
                    <th scope="col">Hayatta mı?</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var musteri in Model)
                {
                    <tr>
                        <td>@musteri.Id</td>
                        <td>@musteri.Ad</td>
                        <td>@musteri.Soyad</td>
                        <td>@musteri.Tckn</td>
                        <td>@musteri.DogumTarihi</td>
                        <td>@musteri.Cinsiyet</td>
                        <td>@musteri.BabaAd</td>
                        <td>@musteri.AnneAd</td>
                        <td>@musteri.SehirAd</td>
                        <td>@musteri.IlceAd</td>
                        <td>@musteri.Semt</td>
                        <td>@musteri.MistralMusteriTipi</td>
                        <td>
                            @if (musteri.HayattaMı)
                            {
                                <span>Evet</span>
                            }
                            else
                            {
                                <span>Hayır</span>
                            }
                        </td>
                        <td>
                            <div class="dropdown">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                    <span>&#8942;</span>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                                    <div style="width:50px; margin-left:30px;text-align:center">
                                        <button type="submit" onclick="openEditModal(@musteri.Id)" class="btn btn-success" style="width:100px;margin:auto; height:30px">Güncelle</button>

                                    <form asp-action="Delete" method="post" onsubmit="return confirm('emin misiniz')" style="display: inline-block;">
                                        <input type="hidden" value="@musteri.Id" name="id">
                                        <button style="width:100px;margin-top:10px; height:30px" type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                            </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<style>
    .table-responsive {
        max-width: 100%;
        overflow-x: auto;
    }

        .table-responsive::-webkit-scrollbar {
            height: 5px; /* Yatay kaydırma çubuğu yüksekliği */
            background-color: #f5f5f5; /* Kaydırma çubuğu arka plan rengi */
        }

        .table-responsive::-webkit-scrollbar-thumb {
            background-color: #888; /* Kaydırma çubuğu rengi */
            border-radius: 5px; /* Kenar yuvarlama */
        }

    .container {
        max-width: 1200px; /* Tablonun genişliğini artırabilirsiniz */
        margin: 0 auto; /* Tabloyu merkezlemek için */
    }
</style>

<script>
    function Create() {

        var url = '@Url.Action("CreateModal", "Musteriler")';
        $.ajax({
            type: 'get',
            url: url
        }).then((result) => {
            $(".modal-content").html(result);
            $("#create").modal('show');
        }).catch((e) => {
            alert("didn't work");
        });
    }

    function openEditModal(id) {
        var url = '/Musteriler/EditModal/' + id;
        console.log(url); // Kontrol için URL'yi yazdır
        $.ajax({
            type: 'get',
            url: url
        }).then((result) => {
            debugger;
            $(".halildeneme").html(result);
            $("#edit").modal('show');
        }).catch((e) => {
            alert("Bir hata oluştu.");
        });
    }
        
    //     function selectIlce() {

    //         var url = '@Url.Action("CreateModalIlce", "Musteriler")';
    //     $.ajax({
    //         type: 'get',
    //         url: url
    //     }).then((result) => {
    //         $(".modal-content").html(result);
    //     }).catch((e) => {
    //         alert("didn't work");
    //     });
    // }



        // // Şehir dropdown listesi değiştiğinde tetiklenecek fonksiyon
        // document.getElementById("sehirDropDown").addEventListener("change", function () {
        //     debugger;
        //     // Seçilen şehir ID'sini al
        //     var secilenSehirId = this.options[this.selectedIndex].getAttribute('itemid');
        //     var url = '/Musteriler/CreateModal';
        //     // AJAX ile ilgili şehrin ilçelerini getir
        //     $.ajax({
        //         url: url, // İlçeleri getirilecek Action'ın URL'si
        //         type: 'GET',
        //         data: { sehirId: secilenSehirId }, // Seçilen şehir ID'sini parametre olarak gönder
        //         success: function (data) {
        //             // Başarılı bir şekilde veriler alındığında yapılacak işlemler
        //             // İlçe dropdown listesini temizle
        //             $('#ilceDropDown').empty();
        //             // Gelen verileri ilçe dropdown listesine ekle
        //             $.each(data, function (key, value) {
        //                 $('#ilceDropDown').append('<option value="' + value.Value + '">' + value.Text + '</option>');
        //             });
        //         },
        //         error: function () {
        //             // Hata durumunda yapılacak işlemler
        //             alert('Bir hata oluştu, ilçeler getirilemedi.');
        //         }
        //     });
        // });
    
</script>

<style>
    .table-responsive {
        max-width: 100%;
        overflow-x: auto;
    }

        .table-responsive::-webkit-scrollbar {
            height: 5px; /* Yatay kaydırma çubuğu yüksekliği */
            background-color: #f5f5f5; /* Kaydırma çubuğu arka plan rengi */
        }

        .table-responsive::-webkit-scrollbar-thumb {
            background-color: #888; /* Kaydırma çubuğu rengi */
            border-radius: 5px; /* Kenar yuvarlama */
        }

    .container {
        max-width: 1200px; /* Tablonun genişliğini artırabilirsiniz */
        margin: 0 auto; /* Tabloyu merkezlemek için */
    }

    .table-responsive::-webkit-scrollbar-track {
        background: #f1f1f1; /* Kaydırma çubuğu izleme arka plan rengi */
    }
</style>